package in.cg.main.enums;

public enum OrderStatus {
	DRAFT_CART,
    CHECKOUT_STARTED,
    PRESCRIPTION_PENDING,
    PRESCRIPTION_APPROVED,
    PRESCRIPTION_REJECTED,
    PAYMENT_PENDING,
    PAYMENT_FAILED,
    PAID,
    PACKED,
    OUT_FOR_DELIVERY,
    DELIVERED,
    CUSTOMER_CANCELLED,
    ADMIN_CANCELLED,
    RETURN_REQUESTED,
    REFUND_INITIATED,
    REFUND_COMPLETED
}
