server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/authDb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      enabled: false

jwt:
  secret: mySuperSecretKeyForJwtThatIsVerySecure1234567890

app:
  mail:
    enabled: ${APP_MAIL_ENABLED:false}
    from: ${APP_MAIL_FROM:${SPRING_MAIL_USERNAME:}}

order:
  service:
    url: ${ORDER_SERVICE_URL:http://localhost:8083}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

# 🔥 LOGGING (IMPORTANT)
logging:
  file:
    name: /app/logs/auth-service.log
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
